const profileData =[
    {
        id : 0,
        imgsrc : "https://media.licdn.com/dms/image/C5603AQHFsWFi-1-DLg/profile-displayphoto-shrink_800_800/0/1516345387410?e=1718236800&v=beta&t=NSsuH8KnQshFSKwN9wY_Pzhj4utYz_fLtyNMZ_t5VyY",
        name: "Shurjeel Tousif",
        title: "Software Engineering Leader | Entrepreneur",
        linkedin: "https://www.linkedin.com/in/shurjeeltousif/",
        email:"shurjeel.tousif@hotmail.co.uk",
        about :"A creative, results-driven, technology executive with a strong academic background and 18 years of multi-industry experience working for the international technology companies in the world using AGILE, SCRUM and SAFE software development lifecycle concepts with the last 10 years developing, managing, inspiring and retaining varying teams of up to 75 FTEs (software development, ",
        interest: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum adipisci consectetur dolorum! Dolor architecto incidunt suscipit modi deleniti, possimus cumque, tenetur quaerat ea soluta, molestias hic quasi? Provident, labore minus.",
    },
    {
        id : 1,
        imgsrc : "https://media.licdn.com/dms/image/D4D03AQEQVA9wADUcRw/profile-displayphoto-shrink_800_800/0/1694774387637?e=1718236800&v=beta&t=0sbiN6pN5Ddu1cmFF6DfDcAsNwT8sJGakggn2rizqQc",
        name: "Shahmeer Khan",
        title: "Pythonista | Backend Engineer ",
        // linkedin: "https://www.linkedin.com/in/meer-khan/",
        email:"shahmirkhan519@gmail.com",
        about :"A creative, results-driven, technology executive with a strong academic background and 18 years of multi-industry experience working for the international technology companies in the world using AGILE, SCRUM and SAFE software development lifecycle concepts with the last 10 years developing, managing, inspiring and retaining varying teams of up to 75 FTEs (software development,",
        interest: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum adipisci consectetur dolorum! Dolor architecto incidunt suscipit modi deleniti, possimus cumque, tenetur quaerat ea soluta, molestias hic quasi? Provident, labore minus.",
    },
    {
        id : 2,
        imgsrc : "https://media.licdn.com/dms/image/D4D03AQE6zJTpPGtRBw/profile-displayphoto-shrink_800_800/0/1672828582372?e=1718236800&v=beta&t=18m8sge_YljB_bhSQFTkcQnG6b3LbpKJtLVejEffiQE",
        name: "Muhammad Arsalan",
        title: "Software Engineer | React.js ",
        linkedin: "https://www.linkedin.com/in/mianarsalan20/",
        // email:"mianarsalan20@gmail.com",
        about :"A creative, results-driven, technology executive with a strong academic background and 18 years of multi-industry experience working for the international technology companies in the world using AGILE, SCRUM and SAFE software development lifecycle concepts with the last 10 years developing, managing, inspiring and retaining varying teams of up to 75 FTEs (software development, ",
        interest: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum adipisci consectetur dolorum! Dolor architecto incidunt suscipit modi deleniti, possimus cumque, tenetur quaerat ea soluta, molestias hic quasi? Provident, labore minus.",
    },
    {
        id : 3,
        imgsrc : "https://media.licdn.com/dms/image/D4D03AQHaIPSaBzB7bg/profile-displayphoto-shrink_800_800/0/1688542662813?e=1718236800&v=beta&t=XwDVnHk1a6iXjuK3pg30VsMQveYi7mpfNQWvgIshiNA",
        name: "Fazle Yazdan",
        title: "Software Quality Assurance Engineer",
        linkedin: "https://www.linkedin.com/in/fazle-yazdan/",
        email:"fazleyazdan345@gmail.com",
        about :"A creative, results-driven, technology executive with a strong academic background and 18 years of multi-industry experience working for the international technology companies in the world using AGILE, SCRUM and SAFE software development lifecycle concepts with the last 10 years developing, managing, inspiring and retaining varying teams of up to 75 FTEs (software development,",
        interest: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum adipisci consectetur dolorum! Dolor architecto incidunt suscipit modi deleniti, possimus cumque, tenetur quaerat ea soluta, molestias hic quasi? Provident, labore minus.",
    },
    {
        id : 4,
        imgsrc : "https://media.licdn.com/dms/image/C4D03AQFkybaM8UIwRg/profile-displayphoto-shrink_800_800/0/1653249081881?e=1718236800&v=beta&t=2fKZ5I_T9xo0QFJ30jvNx0FDgzgIIg9p_QBuHxTj9s4",
        name: "Raiha Narmeen",
        title: "SQA Engineer | Code Analyzer",
        linkedin: "https://www.linkedin.com/in/raiha-n-7199a9187/",
        email:"imraiha18@gmail.com",
        about :"A creative, results-driven, technology executive with a strong academic background and 18 years of multi-industry experience working for the international technology companies in the world using AGILE, SCRUM and SAFE software development lifecycle concepts with the last 10 years developing, managing, inspiring and retaining varying teams of up to 75 FTEs (software development,",
        interest: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum adipisci consectetur dolorum! Dolor architecto incidunt suscipit modi deleniti, possimus cumque, tenetur quaerat ea soluta, molestias hic quasi? Provident, labore minus.",
    },
    {
        id : 5,
        imgsrc : "https://media.licdn.com/dms/image/C4D03AQHEikNrm6X9jg/profile-displayphoto-shrink_800_800/0/1652329297684?e=1718236800&v=beta&t=-ZP_3wrpuERBNwni8w8CRnpdYiIaF-uzgaVMsDBLsOU",
        name: "Jawad Khan",
        title: "Software Engineer | QA Best Practices",
        // linkedin: "https://www.linkedin.com/in/fazle-yazdan/",
        email:"jawad.jk245@gmail.com",
        about :"A creative, results-driven, technology executive with a strong academic background and 18 years of multi-industry experience working for the international technology companies in the world using AGILE, SCRUM and SAFE software development lifecycle concepts with the last 10 years developing, managing, inspiring and retaining varying teams of up to 75 FTEs (software development,",
        interest: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum adipisci consectetur dolorum! Dolor architecto incidunt suscipit modi deleniti, possimus cumque, tenetur quaerat ea soluta, molestias hic quasi? Provident, labore minus.",
    },
    {
        id : 6,
        imgsrc : "https://media.licdn.com/dms/image/C5603AQG65QC7B7Tnfg/profile-displayphoto-shrink_800_800/0/1563093429060?e=1718236800&v=beta&t=A6FXVbA6jLZrbkwUGGTPu5LG2f4t3wvPufRBRJVDrZ8",
        name: "Uzair Khan",
        title: "Python Backend Developer",
        linkedin: "https://www.linkedin.com/in/uzzaykhan/",
        email:"uk78618@gmail.com",
        about :"👋 Hi there!A creative, results-driven, technology executive with a strong academic background and 18 years of multi-industry experience working for the international technology companies in the world using AGILE, SCRUM and SAFE software development lifecycle concepts with the last 10 years developing, managing, inspiring and retaining varying teams of up to 75 FTEs (software development,",
        interest: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum adipisci consectetur dolorum! Dolor architecto incidunt suscipit modi deleniti, possimus cumque, tenetur quaerat ea soluta, molestias hic quasi? Provident, labore minus.",
    },
    {
        id : 7,
        imgsrc : "https://media.licdn.com/dms/image/D4E03AQEPcY5aP9PD6A/profile-displayphoto-shrink_400_400/0/1710913976890?e=1718236800&v=beta&t=leWe1QeWIJTCuIE7JY_1PR1YVta-UT_CArOxZCUOXts",
        name: "Muhammad Kamran ",
        title: "Linux System and DevOps Engineer",
        // linkedin: "https://www.linkedin.com/in/muhammad-kamran-1612802b1/",
        email:"hinakami068@gmail.com",
        about :"A creative, results-driven, technology executive with a strong academic background and 18 years of multi-industry experience working for the international technology companies in the world using AGILE, SCRUM and SAFE software development lifecycle concepts with the last 10 years developing, managing, inspiring and retaining varying teams of up to 75 FTEs (software development,",
        interest: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum adipisci consectetur dolorum! Dolor architecto incidunt suscipit modi deleniti, possimus cumque, tenetur quaerat ea soluta, molestias hic quasi? Provident, labore minus.",
    }
    ,
]

export default profileData;